# Generated by cpp11: do not edit by hand

extract_all_binary_combinations <- function(n) {
  .Call(`_Watershed_extract_all_binary_combinations`, n)
}

extract_all_binary_combinations_ignoring_one_row <- function(n, column_to_ignore) {
  .Call(`_Watershed_extract_all_binary_combinations_ignoring_one_row`, n, column_to_ignore)
}

extract_all_binary_combinations_ignoring_two_row <- function(n, column_to_ignore1, column_to_ignore2) {
  .Call(`_Watershed_extract_all_binary_combinations_ignoring_two_row`, n, column_to_ignore1, column_to_ignore2)
}

un_normalized_crf_weight <- function(all_binary_combinations_matrix, combination_number, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool) {
  .Call(`_Watershed_un_normalized_crf_weight`, all_binary_combinations_matrix, combination_number, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool)
}

exact_normalization_constant <- function(feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool) {
  .Call(`_Watershed_exact_normalization_constant`, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool)
}

exact_probability <- function(normalization_constant, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, combination_number, all_binary_combinations_ignoring_one_row, posterior_bool) {
  .Call(`_Watershed_exact_probability`, normalization_constant, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, combination_number, all_binary_combinations_ignoring_one_row, posterior_bool)
}

exact_marginal_probability <- function(normalization_constant, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool) {
  .Call(`_Watershed_exact_marginal_probability`, normalization_constant, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool)
}

exact_marginal_pairwise_probability <- function(normalization_constant, dimension1, dimension2, dimension_counter, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool) {
  .Call(`_Watershed_exact_marginal_pairwise_probability`, normalization_constant, dimension1, dimension2, dimension_counter, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool)
}

update_marginal_probabilities_exact_inference_cpp <- function(feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool) {
  .Call(`_Watershed_update_marginal_probabilities_exact_inference_cpp`, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool)
}

compute_crf_likelihood_exact_inference_cpp <- function(posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton) {
  .Call(`_Watershed_compute_crf_likelihood_exact_inference_cpp`, posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton)
}

un_normalized_pseudolikelihood_crf_weight <- function(dimension, combination_number, feat, posterior, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool) {
  .Call(`_Watershed_un_normalized_pseudolikelihood_crf_weight`, dimension, combination_number, feat, posterior, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool)
}

exact_pseudolikelihood_normalization_constant <- function(feat, discrete_outliers, posterior, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool) {
  .Call(`_Watershed_exact_pseudolikelihood_normalization_constant`, feat, discrete_outliers, posterior, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool)
}

exact_pseudolikelihood_marginal_probability <- function(normalization_constant, feat, discrete_outliers, posterior, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool) {
  .Call(`_Watershed_exact_pseudolikelihood_marginal_probability`, normalization_constant, feat, discrete_outliers, posterior, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool)
}

update_pseudolikelihood_marginal_probabilities_exact_inference_cpp <- function(feat, discrete_outliers, posterior, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool) {
  .Call(`_Watershed_update_pseudolikelihood_marginal_probabilities_exact_inference_cpp`, feat, discrete_outliers, posterior, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool)
}

compute_pseudolikelihood_crf_likelihood_exact_inference_cpp <- function(posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton) {
  .Call(`_Watershed_compute_pseudolikelihood_crf_likelihood_exact_inference_cpp`, posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton)
}

variational_update <- function(sample_num, dimension, feat, discrete_outliers, probabilities, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, posterior_bool) {
  .Call(`_Watershed_variational_update`, sample_num, dimension, feat, discrete_outliers, probabilities, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, posterior_bool)
}

variational_optimization <- function(probabilities, sample_num, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, posterior_bool, step_size, convergence_thresh, g) {
  .Call(`_Watershed_variational_optimization`, probabilities, sample_num, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, posterior_bool, step_size, convergence_thresh, g)
}

update_marginal_probabilities_vi_cpp <- function(feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, step_size, convergence_thresh, probability_init, posterior_bool) {
  .Call(`_Watershed_update_marginal_probabilities_vi_cpp`, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, step_size, convergence_thresh, probability_init, posterior_bool)
}

un_normalized_independent_crf_weight <- function(dimension, combination_number, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool) {
  .Call(`_Watershed_un_normalized_independent_crf_weight`, dimension, combination_number, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, posterior_bool)
}

exact_independent_normalization_constant <- function(feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool) {
  .Call(`_Watershed_exact_independent_normalization_constant`, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool)
}

exact_independent_marginal_probability <- function(normalization_constant, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool) {
  .Call(`_Watershed_exact_independent_marginal_probability`, normalization_constant, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, sample_num, dimension, posterior_bool)
}

update_independent_marginal_probabilities_exact_inference_cpp <- function(feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool) {
  .Call(`_Watershed_update_independent_marginal_probabilities_exact_inference_cpp`, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool)
}

compute_independent_crf_likelihood_exact_inference_cpp <- function(posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton) {
  .Call(`_Watershed_compute_independent_crf_likelihood_exact_inference_cpp`, posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton)
}

logistic_regression_normalization_constant <- function(feat, intercept, theta, sample_num) {
  .Call(`_Watershed_logistic_regression_normalization_constant`, feat, intercept, theta, sample_num)
}

compute_logistic_regression_likelihood_exact_inference_cpp <- function(posterior, feat, intercept, theta, lambda) {
  .Call(`_Watershed_compute_logistic_regression_likelihood_exact_inference_cpp`, posterior, feat, intercept, theta, lambda)
}

logistic_regression_predictions <- function(feat, intercept, theta) {
  .Call(`_Watershed_logistic_regression_predictions`, feat, intercept, theta)
}
