# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_all_binary_combinations <- function(n) {
    .Call(`_Watershed_extract_all_binary_combinations`, n)
}

update_marginal_probabilities_exact_inference_cpp <- function(feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool) {
    .Call(`_Watershed_update_marginal_probabilities_exact_inference_cpp`, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool)
}

compute_crf_likelihood_exact_inference_cpp <- function(posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton) {
    .Call(`_Watershed_compute_crf_likelihood_exact_inference_cpp`, posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton)
}

update_pseudolikelihood_marginal_probabilities_exact_inference_cpp <- function(feat, discrete_outliers, posterior, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool) {
    .Call(`_Watershed_update_pseudolikelihood_marginal_probabilities_exact_inference_cpp`, feat, discrete_outliers, posterior, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool)
}

compute_pseudolikelihood_crf_likelihood_exact_inference_cpp <- function(posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton) {
    .Call(`_Watershed_compute_pseudolikelihood_crf_likelihood_exact_inference_cpp`, posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton)
}

update_marginal_probabilities_vi_cpp <- function(feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, step_size, convergence_thresh, probability_init, posterior_bool) {
    .Call(`_Watershed_update_marginal_probabilities_vi_cpp`, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, step_size, convergence_thresh, probability_init, posterior_bool)
}

update_independent_marginal_probabilities_exact_inference_cpp <- function(feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool) {
    .Call(`_Watershed_update_independent_marginal_probabilities_exact_inference_cpp`, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, number_of_pairs, posterior_bool)
}

compute_independent_crf_likelihood_exact_inference_cpp <- function(posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton) {
    .Call(`_Watershed_compute_independent_crf_likelihood_exact_inference_cpp`, posterior, posterior_pairwise, feat, discrete_outliers, theta_singleton, theta_pair, theta, phi_inlier, phi_outlier, number_of_dimensions, lambda, lambda_pair, lambda_singleton)
}

compute_logistic_regression_likelihood_exact_inference_cpp <- function(posterior, feat, intercept, theta, lambda) {
    .Call(`_Watershed_compute_logistic_regression_likelihood_exact_inference_cpp`, posterior, feat, intercept, theta, lambda)
}

logistic_regression_predictions <- function(feat, intercept, theta) {
    .Call(`_Watershed_logistic_regression_predictions`, feat, intercept, theta)
}

